testTorun/testTorun/Pages/univeristies/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using aspDotNetApp.Application.ManageUniveristy;
using aspDotNetApp.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace aspDotNetAppp.Pages.univeristies
{
    public class EditModel : PageModel
    {
        private readonly IMangerUniveristy imangerUni;
        [BindProperty(SupportsGet = true)]
        public Universties uni { set; get; }
        public string Name { set; get; }
        [BindProperty(SupportsGet = true)]
        public string Address { set; get; }
        
        public EditModel(IMangerUniveristy imangerUni)
        {
            this.imangerUni = imangerUni;
        }
        [BindProperty(SupportsGet = true)]
        public bool EditFlag { set; get; }
        public void OnGet(int IdForUniveristy = 0)
        {
            if(IdForUniveristy == 0)
            {
                EditFlag = false;
            }
            else
            {
                EditFlag = true;
                uni = imangerUni.SingleUniveristyDetails(IdForUniveristy);
                
            }
            var i = EditFlag == true ? true : false;
            
        }
        //public bool i = EditFlag == true ? true : false;
        public IActionResult OnPost()
        {
           
            if(EditFlag)
            {
                var EditedUni = new Universties() { id = uni.id, name = uni.name, address = uni.address };
                imangerUni.EditUni(EditedUni);
                return RedirectToPage("./Univerties");
            }
            else
            {
                var CreatedUni = new Universties() { name = uni.name, address = uni.address };
                imangerUni.addUni(CreatedUni);
                return RedirectToPage("./Univerties");
            }
            //return default;
        }
    }
}

testTorun/testTorun/Pages/univeristies/EditAndCreateStudents.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace aspDotNetAppp.Pages.univeristies
{
    public class EditAndCreateStudentsModel : PageModel
    {
        public string AddedName { set; get; }
        public string AddedAddress { set; get; }
        public float AddedGrades { set; get; }
        public void OnGet()
        {
        }
    }
}

testTorun/testTorun/Pages/univeristies/Students.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using aspDotNetApp.Application.ManageStudents;
using aspDotNetApp.Application.ManageUniveristy;
using aspDotNetApp.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace aspDotNetAppp.Pages.univeristies
{
    public class StudentsModel : PageModel
    {
      
        public readonly IStudentInterface imanagerStudent;
        [BindProperty(SupportsGet = true)]
        public string SearchValue { set; get; }
        public Students StudentDetail { set; get; }
        public List<Students> AllStudents { set; get; }
        [BindProperty(SupportsGet = true)]
        public Students stud { set; get; }
        [BindProperty(SupportsGet = true)]
        public int UniID { set; get; }
        [BindProperty(SupportsGet = true)]
        public string reset { set; get; }
        public StudentsModel(IStudentInterface imanagerStudent)
        {
            this.imanagerStudent = imanagerStudent;
            AllStudents = new List<Students>();
            stud = new Students();
        }
        public void OnGet(int StudentID,int UniID,string search)
        {
            StudentDetail = imanagerStudent.GetSingleStudent(UniID);
            AllStudents = imanagerStudent.GetStudentsOfOneUniveristy(UniID);
            //AllStudents = imanagerStudent.GetAllStudents();
            this.UniID = UniID;
           

            
        }
        public IActionResult OnPostDelete(int studentID)
        {
            imanagerStudent.DeleteStudent(studentID);
            return RedirectToPage("./Univerties");
        }
        public IActionResult OnPostSearch(string search = "")
        {
            reset = search;
            AllStudents = imanagerStudent.GetSearchedStudents(this.UniID, this.SearchValue);
            if (AllStudents.Count == 0)
            {
                return RedirectToPage("./StudentsNotFound");
            }
            else if(reset == "reset")
            {
                AllStudents = imanagerStudent.GetStudentsOfOneUniveristy(this.UniID);
                return default;
            }
            else
            {
                AllStudents = imanagerStudent.GetSearchedStudents(this.UniID, this.SearchValue);
                return default;
            }
            
        }
        public IActionResult OnPostStud()
        {

            imanagerStudent.AddingStudentToUni(UniID, stud);
             return RedirectToPage("./Univerties");
        }
    }
}

testTorun/testTorun/Pages/univeristies/StudentsNotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using aspDotNetApp.Application.ManageStudents;
using aspDotNetApp.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace aspDotNetAppp.Pages.univeristies
{
    public class StudentsNotFoundModel : PageModel

    {
        
        public readonly IStudentInterface imangeStudents;
        [BindProperty(SupportsGet = true)]
        public int UniID { set; get; }
        [BindProperty(SupportsGet = true)]
        public string NewName { set; get; }
        [BindProperty(SupportsGet = true)]
        public string NewAddress { set; get; }
        [BindProperty(SupportsGet = true)]
        public float NewGrades { set; get; }
        [BindProperty(SupportsGet = true)]
        
        public Students stud { set; get; }
        [BindProperty(SupportsGet =true)]
        public bool create { set; get; }
        
        //public Students stud { set; get; }
        public StudentsNotFoundModel(IStudentInterface imangeStudents)
        {
            this.imangeStudents = imangeStudents;
            stud = new Students();
        }
        public void OnGet(int UniID, bool create = false)
        {
            if (create)
            {
                this.UniID = UniID;
                stud = new Students();
                this.create = create;
            }
            else
            {
                this.UniID = UniID;
                stud = imangeStudents.GetSingleStudent(UniID);
            }
            /*this.UniID = UniID;
            stud = new Students();
            this.create = create;*/
        }
        public IActionResult OnPost()
        {
            if (create)
            {
                imangeStudents.AddingStudentToUni(UniID, stud);
                return RedirectToPage("./Univerties");
            }
            else
            {
                imangeStudents.EditStudent(this.UniID, stud);
                return RedirectToPage("./Univerties");
            }
            
            
            
        }
    }
}

testTorun/testTorun/Pages/univeristies/UniveristyNotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace aspDotNetAppp.Pages.univeristies
{
    public class UniveristyNotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

testTorun/testTorun/Pages/univeristies/Univerties.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using aspDotNetApp.Application.ManageUniveristy;
using aspDotNetApp.Data;
using aspDotNetApp.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace testTorun.Pages.univeristies
{
    public class UnivertiesModel : PageModel
    {
        
        public string message { set; get; }
        private readonly IConfiguration config;
        [BindProperty(SupportsGet = true)]
        public string searchByName { set; get; }
       
        public List<Universties> Univeristies { set; get; }
        public readonly IMangerUniveristy ImanagerUniveristy;
        [BindProperty(SupportsGet = true)]
        public string AddedName { set; get; }
        [BindProperty(SupportsGet = true)]
        public string AddedAddress { set; get; }
        public string directon { set; get; }
        

        public UnivertiesModel(IConfiguration con,IMangerUniveristy ImanagerUniveristy)
        {
            config = con;
            this.ImanagerUniveristy = ImanagerUniveristy;
        }
        public IActionResult OnGet(string search,int IdForDelete = 0)
        {
        
            if (search == "reset")
            {
                Univeristies = this.ImanagerUniveristy.GetUniversties();
            }
            else if(this.searchByName == null)
            {
                Univeristies = this.ImanagerUniveristy.GetUniversties();
                
            }
            else
            {
                Univeristies = this.ImanagerUniveristy.GetUniveristyByName(this.searchByName);
            }
            if(IdForDelete != 0)
            {
                ImanagerUniveristy.deleteUni(IdForDelete);
                return RedirectToPage("./Univerties");
            }
            return default;
            
        }
        public IActionResult OnPost()
        {
            
            var uni = new Universties() { name = AddedName, address = AddedAddress };
            ImanagerUniveristy.addUni(uni);
            return RedirectToPage("./Univerties");
        }
    }
}

testTorun/testTorun/Pages/univeristies/details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using aspDotNetApp.Application.ManageUniveristy;
using aspDotNetApp.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace aspDotNetAppp.Pages.univeristies
{
    public class detailsModel : PageModel
    {
        public Universties DeatilsUni { get; set; }
        private readonly IMangerUniveristy Imanager;
        public detailsModel(IMangerUniveristy Imanager)
        {
            this.Imanager = Imanager;
        }
        public IActionResult OnGet(int IdForUniveristy)
        {
            DeatilsUni = Imanager.SingleUniveristyDetails(IdForUniveristy);
            if(DeatilsUni == null)
            {
                return RedirectToPage("./UniveristyNotFound");
            }
            else
            {
                return Page();
            }
        }
    }
}

testTorun/testTorun/Pages/univeristies/Edit.cshtml
@page
@model aspDotNetAppp.Pages.univeristies.EditModel
@{
}
<form method="post">
    <input type="hidden" asp-for="@Model.EditFlag" />
    <a class="btn btn-danger" asp-page="./Univerties">GO BACK</a>
    <br /><br />
    <input type="hidden" asp-for="@Model.uni.id." />
    <label>NAME:</label>
    <input type="text" class="input-group" asp-for="@Model.uni.name"/>
    <label>ADDRESS:</label>
    <input type="text" class="input-group" asp-for="@Model.uni.address"/>
    <br /><br />
    <button  type="submit" class="btn btn-primary">Finish</button>

</form>

testTorun/testTorun/Pages/univeristies/EditAndCreateStudents.cshtml
@page
@model aspDotNetAppp.Pages.univeristies.EditAndCreateStudentsModel
@{
}
<form method="post"class="form-group">
    <label>Your name</label>
    <input type="text" class="form-control"asp-for="@Model.AddedName" />
    <label>Your Name</label>
    <input type="text" class="form-control"asp-for="@Model.AddedAddress" />
    <label>Your Grades</label>
    <input type="text"class="form-control" asp-for="@Model.AddedGrades" />
    <button type="submit"class="btn btn-primary">Finish</button>
</form>

testTorun/testTorun/Pages/univeristies/Students.cshtml
@page
@model aspDotNetAppp.Pages.univeristies.StudentsModel
@{
}
<form class="form-group" asp-page-handler="Search" method="post">
    <input type="hidden" asp-for="@Model.UniID" />
    <input class="form-control" type="search" asp-for="@Model.SearchValue" />
    <button type="submit" class="btn btn-primary" asp-page-handler="Search">Search </button>
    <button type="submit" asp-route-search="reset" asp-page-handler="Search" class="btn btn-primary">reset</button>
</form>
<p>STUDENTS</p>
<table class="table">
    <tr>
        <td class="font-weight-bold">ID</td>
        <td class="font-weight-bold">NAME</td>
        <td class="font-weight-bold">Grades</td>
        <td class="font-weight-bold">EDIT</td>
        <td class="font-weight-bold">DELETE</td>
    </tr>
    @foreach (var stud in Model.AllStudents)
    {
        <tr>

            <td>@stud.id</td>
            <td>@stud.name</td>
            <td>@stud.grades</td>
            
            <td><a asp-page="./StudentsNotFound"asp-route-UniID="@stud.id">Edit</a></td>
            <form method="post">
                <td><button class="btn btn-primary" type="submit" asp-page-handler="Delete" asp-route-StudentID="@stud.id">Delete</button></td>
            </form>
            

        </tr>
    }
</table>
<h2>Add Students</h2>

<form asp-page-handler="Stud" method="post" class="form-group">
    <input type="hidden" asp-for="@Model.UniID" />
    <label>Your Name</label>
    <input type="text" class="form-control" asp-for="@Model.stud.name" />
    <label>Your Grades</label>
    <input type="text" class="form-control" asp-for="@Model.stud.grades" />
    <button asp-page-handler="Stud"  type="submit" class="btn btn-primary">Finish</button>
</form>
<a class="btn btn-primary" asp-page="./Univerties">
    back
</a>

testTorun/testTorun/Pages/univeristies/StudentsNotFound.cshtml
@page
@model aspDotNetAppp.Pages.univeristies.StudentsNotFoundModel
@{
}
<h1>Students Not Found</h1>
<form method="post" class="form-group">
    <input type="hidden" asp-for="@Model.UniID" />
    <label>Your Name</label>
    <input type="text" class="form-control" asp-for="@Model.stud.name" />
    <label>Your Grades</label>
    <input type="text" class="form-control" asp-for="@Model.stud.grades" />
    <input type="hidden" asp-for="@Model.create" />
    <button type="submit" class="btn btn-primary">Finish</button>
</form>
<a class="btn btn-primary" asp-page="./Univerties">Back To Univeristies</a>

testTorun/testTorun/Pages/univeristies/UniveristyNotFound.cshtml
@page
@model aspDotNetAppp.Pages.univeristies.UniveristyNotFoundModel
@{
}
<h3>
    Univeristy Not Found
</h3>
<a asp-page="./Univerties">
    Back To Universties
</a>

testTorun/testTorun/Pages/univeristies/Univerties.cshtml
@page
@model testTorun.Pages.univeristies.UnivertiesModel
@{
}
<form method="get" class="form-group">

    <input class="form-control" type="search" placeholder="search here" asp-for="searchByName" />

    <a class="btn btn-danger"asp-page="./Univerties" asp-route-search="reset">reset</a>
    <button class="btn btn-primary"  value="search">search</button>


</form >
<table class="table">
    <tr>
        <td class="font-weight-bold">ID</td>
        <td class="font-weight-bold">NAME</td>
        <td class="font-weight-bold">ADDRESS</td>
        <td class="font-weight-bold">STUDENTS</td>
        <td class="font-weight-bold">COUNT OF STUDENTS</td>
        <td class="font-weight-bold">DETAILS</td>
        <td class="font-weight-bold">EDIT</td>
        <td class="font-weight-bold">DELETE</td>
    </tr>

    @foreach (var uni in Model.Univeristies)
    {
<tr>
    <td>@uni.id</td>
    <td>@uni.name</td>
    <td>@uni.address</td>
    @if (uni.students.Count == 0)
    {
        <td><a asp-page="./StudentsNotFound"asp-route-create="@true"asp-route-StudentID="@uni.id" asp-route-UniID="@uni.id">Students</a></td>
    }
    else
    {
        <td><a asp-page="./Students" asp-route-StudentID="@uni.id" asp-route-UniID="@uni.id">Students</a></td>
    }
    <td>@uni.students.Count</td>
    <td>
        <a asp-page="./details" asp-route-IdForUniveristy="@uni.id">
            details
        </a>
    <td>
        <a asp-page="./Edit" asp-route-IdForUniveristy="@uni.id">
            Edit
        </a>
    </td>
    <td>
        <a asp-page="./Univerties" asp-route-IdForDelete="@uni.id">
            Delete
        </a>
    </td>
</tr>


    }
</table>
<br />
<h2>Add New Univeristy </h2>
@*<form method="post">
    <input class="form-control" type="text" placeholder="Univeristy name"asp-for="AddedName">
    <input class="form-control" type="text"placeholder="Address"asp-for="AddedAddress">
    <button type="submit" class="btn btn-primary">Submit</button>
</form>*@
<a asp-page="./Edit" class="btn btn-primary">Create Univeristy</a>

testTorun/testTorun/Pages/univeristies/details.cshtml
@page
@model aspDotNetAppp.Pages.univeristies.detailsModel
@{
}


<p> ID is : @Model.DeatilsUni.id</p>
<p> Name is : @Model.DeatilsUni.name</p>
<p> Address is : @Model.DeatilsUni.address</p>
<a asp-page="Univerties">back one step</a>